//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Database
    {
        public Database()
        {
            this.ServerDatabase = new HashSet<ServerDatabase>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> LstOltpUpdateDate { get; set; }
        public Nullable<System.DateTime> LstDataMartUpdateDate { get; set; }
        public string LstUpdateError { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string DbGroup { get; set; }
        public int EnterpriseId { get; set; }
    
        public virtual ICollection<ServerDatabase> ServerDatabase { get; set; }
        public virtual Enterprise Enterprise { get; set; }
    }
}
