//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Payment = new HashSet<Payment>();
        }
    
        public int Id { get; set; }
        public int Owner { get; set; }
        public Nullable<int> Reseller { get; set; }
        public string BillingName { get; set; }
        public string BillingAdressLine1 { get; set; }
        public string BillingAdressLine2 { get; set; }
        public string BillingCity { get; set; }
        public string BillingState { get; set; }
        public string BillingZIP { get; set; }
        public string BillingCountry { get; set; }
        public string TaxId { get; set; }
        public string Description { get; set; }
        public string Mod { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int Status { get; set; }
        public string Detail { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<Payment> Payment { get; set; }
    }
}
