//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Server
    {
        public Server()
        {
            this.ServerDatabase = new HashSet<ServerDatabase>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> LastSeenDate { get; set; }
        public int Failed { get; set; }
        public int Priority { get; set; }
        public bool Enabled { get; set; }
        public Nullable<int> EnterpriseId { get; set; }
        public string Url { get; set; }
    
        public virtual ICollection<ServerDatabase> ServerDatabase { get; set; }
        public virtual Enterprise Enterprise { get; set; }
    }
}
