//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAddress
    {
        public int UserId { get; set; }
        public string AdressLine1 { get; set; }
        public string AdressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZIP { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string BillingName { get; set; }
        public string BillingAdressLine1 { get; set; }
        public string BillingAdressLine2 { get; set; }
        public string BillingCity { get; set; }
        public string BillingState { get; set; }
        public string BillingZIP { get; set; }
        public string BillingCountry { get; set; }
        public string TaxId { get; set; }
        public string Name { get; set; }
    
        public virtual User User { get; set; }
    }
}
