//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Enterprise = new HashSet<Enterprise>();
            this.Enterprise1 = new HashSet<Enterprise>();
            this.UserEnterprise = new HashSet<UserEnterprise>();
            this.Order = new HashSet<Order>();
            this.Order1 = new HashSet<Order>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    
        public virtual ICollection<Enterprise> Enterprise { get; set; }
        public virtual ICollection<Enterprise> Enterprise1 { get; set; }
        public virtual ICollection<UserEnterprise> UserEnterprise { get; set; }
        public virtual UserAddress UserAddress { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<Order> Order1 { get; set; }
    }
}
