//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEnterprise
    {
        public int Id { get; set; }
        public int EnterpriseId { get; set; }
        public bool AdminRole { get; set; }
        public bool DataLoaderRole { get; set; }
        public bool ReportViewerRole { get; set; }
        public bool DataMartLoaderRole { get; set; }
        public int UserId { get; set; }
    
        public virtual Enterprise Enterprise { get; set; }
        public virtual User User { get; set; }
    }
}
